scalar LocalDate

enum TYPE {
  POST
  COMMENT
}

type Message {
  id: String!
  description: String!
  authors: [Author!]!
  date: LocalDate
  replyTo: Message
  type: TYPE!
  active: Boolean
  numberOfComments: Int
  cost: Float
}

type Author {
  id: String!
  name: String!
  adress: Adress
}

type Adress {
  street: String!
  city: String!
  country: String
}

type Query {
  messages(tab: String!): [Message]
}

input CreateMessageInput {
  description: String!
}

type Mutation {
  createMessage(args: CreateMessageInput!): Message
  approve(id: ID!): Message
  decline(id: ID!, reason: String!): Message
  escalate(id: ID!): Message
}

schema {
  query: Query
  mutation: Mutation
}
