scalar LocalDate

enum TYPE {
  POST
  COMMENT
}

type Message {
  id: String!
  description: String!
  authors: [Author!]!
  date: LocalDate
  replyTo: Message
  type: TYPE!
  active: Boolean
  comments: [String]!
  numberOfComments: Int
  cost: Float
  food: Food
}

union Food = Potato | Tomato

type Potato {
  id: ID!
  size: Int!
  color: String!
}

type Tomato {
  id: ID!
  size: Int!
  origin: Address!
}

type Author {
  id: String!
  name: String!
  address: Address
}

type Address {
  street: String!
  city: String!
  country: String
}

type Query {
  messages(tab: String!): [Message]
}

input CreateMessageInput {
  description: String!
}

type Mutation {
  createMessage(args: CreateMessageInput!): Message
  approve(id: ID!): Message
  decline(id: ID!, reason: String!): Message
  escalate(id: ID!): Message
}

schema {
  query: Query
  mutation: Mutation
}
